[versions]
spring = "3.2.5"
postgresql = "42.7.8"
lombok = "1.18.42"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring" }

[libraries]
# Spring
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring" }

# Database
database-runtime = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

# Lombok
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[bundles]
spring = ["spring-boot-starter-web", "spring-boot-starter-actuator"]
